chore(zsh): sync-history

diff --git a/bin/sync-hist b/bin/sync-hist
--- a/bin/sync-hist
+++ b/bin/sync-hist
@@ -1,27 +1,47 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env bash
 
 # This allows to quickly restart the DNS responder e.g. when SSH host is not recognized.
 
-set -xeo pipefail
+set -eo pipefail
 
 source $YASLI_DIR/logging.inc.sh
 
+log_info "Fetching results"
+
 cd $HOME/.zsh_history_proj
-git fetch --all
-git reset --hard origin/main
+
+(
+    git fetch --all
+    git reset --hard origin/main
+) 2>&1 | log_cmd || log_fail "Failed"
+
+log_info "Decrypting"
 
 HIST_SYNC_DEFAULT_GPG="${HIST_SYNC_DEFAULT_GPG:-unspecified}"
 
-gpg -r $HIST_SYNC_DEFAULT_GPG --output zsh_history_decrypted --decrypt zsh_history
+(
+    gpg --batch --yes --output zsh_history_decrypted --decrypt zsh_history
+) 2>&1 | log_cmd || log_fail "Failed"
 
-builtin fc -R -I "./zsh_history_decrypted"
-builtin fc -W "$HISTFILE"
+zsh -c "builtin fc -R -I './zsh_history_decrypted'"
+zsh -c "builtin fc -W '$HISTFILE'"
 
 [ -f $HISTFILE ] || log_fail "No $HISTFILE to encrypt"
 
 cp $HISTFILE $HISTFILE.bak
 
-gpg -r $HIST_SYNC_DEFAULT_GPG --output zsh_history --encrypt $HISTFILE
+log_info "Copied history backup to $HISTFILE.bak"
+(
+    log_info "Encrypting"
+    gpg --batch --yes -r $HIST_SYNC_DEFAULT_GPG --output zsh_history --encrypt $HISTFILE
+) 2>&1 | log_cmd || log_fail "Failed"
 
-git commit -am "upd history $(date)"
-git push --force
+log_info "Committing"
+(
+    git commit -am "upd history $(date)"
+    git push --force
+) 2>&1 | log_cmd || log_fail "Failed"
+
+log_success "Done"
+
+
